# powerline-status
- name: "Ensure latest powerline-status package"
  pip: name=powerline-status state=latest executable=pip3
  register: powerline_package
  notify: powerline reload

- name: "Register powerline location"
  shell: "[ -d $(pip show powerline-status | grep 'Location' | awk '{print $2}')/powerline ] && echo $(pip show powerline-status | grep 'Location' | awk '{print $2}')/powerline"
  register: powerline_package_location
  check_mode: no
  changed_when: false

- name: "Ensure ~/.config/powerline/ directory present"
  file: path=~/.config/powerline state=directory
  register: powerline_config_directory

- name: "Ensure latest ~/.config/powerline/config.json"
  template:
    src: dot_config_powerline_config.json.j2
    dest: ~/.config/powerline/config.json
  register: powerline_config

- name: "Ensure latest powerline-fonts"
  git:
    repo: https://github.com/powerline/fonts.git
    dest: "{{ powerline_config_directory.path }}/powerline-fonts/"
  register: powerline_fonts_repo

- name: "Ensure latest powerline-status Hack font in ~/Library/Fonts/"
  copy:
    src: "{{ powerline_config_directory.path }}/powerline-fonts/Hack"
    dest: ~/Library/Fonts/Hack

