# pip
- name: "Ensure pip3 default pip"
  file:
    src: /usr/local/bin/pip3
    dest: /usr/local/bin/pip
    state: link

- name: "Ensure latest pip with pip"
  pip: name=pip state=latest


- name: "Ensure ~/.pip/ directory present"
  file: path=~/.pip state=directory

- name: "Ensure ~/.pip/pip.cfg latest"
  template: src=pip.conf.j2 dest=~/.pip/pip.conf
