# tmux
- name: "Ensure latest tmux package"
  homebrew: name=tmux state=latest

- name: "Ensure ~/.tmux.conf latest"
  template: src=dot_tmux.j2 dest=~/.tmux.conf
  when: powerline_package_location is defined
