# Ansible
- name: "Ensure latest ansible with pip"
  pip: name=ansible state=latest

- name: "Ensure skel ~/.ansible/"
  file:
    path: ~/.ansible/{{item}}
    state: directory
  with_items:
    - modules
    - plugins

- name: "Ensure defaults in  ~/.ansible/ansible.cfg"
  blockinfile:
    dest: ~/.ansible/ansible.cfg
    content: "{{ lookup('template', 'ansible.cfg.j2') }}"
    insertbefore: BOF
    create: yes

- name: "Ensure defaults in ~/.ansible/inventory"
  blockinfile:
    dest: ~/.ansible/inventory
    content: "{{ lookup('template', 'ansible_default_inventory.j2') }}"
    insertbefore: BOF
    create: yes
