# vim
- name: "iPython"
  block:
    - name: "Ensure latest ipython package with pip"
      pip: name=ipython state=latest

    - name: "Ensure directories in ~/.ipython/"
      file:
        path: ~/{{ item }}
        state: directory
      with_items:
        - .ipython
        - .ipython/profile_default
        - .ipython/profile_default/startup

    - name: "Ensure latest in ~/.ipython/ files"
      copy: src=vim/ dest=~/.vim/

    - name: "Ensure vim-plug latest plug-vim"
      get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest=~/.vim/autoload/plug.vim
