# Tasks to include
#
# sh -c "$(head -4 main.yaml | tail -1 | sed 's/^# //')"
# head -5 main.yaml > new.main.yaml && for var in $(ls | grep -v "main.yaml" | sed 's/\.yaml$//' | sort); do printf "%s include_tasks: %s.yaml\n  tags: %s\n\n" "-" "${var}" "${var}";done >> new.main.yaml && mv new.main.yaml main.yaml
#
- include_tasks: ansible.yaml
  tags: ansible

- include_tasks: bash.yaml
  tags: bash

- include_tasks: git.yaml
  tags: git

- include_tasks: gitmultirepo.yaml
  tags: gitmultirepo

- include_tasks: google_chrome.yaml
  tags: google_chrome

- include_tasks: homebrew.yaml
  tags: homebrew

- include_tasks: iterm2.yaml
  tags: iterm2

- include_tasks: karabiner-elements.yaml
  tags: karabiner-elements

- include_tasks: pip.yaml
  tags: pip

- include_tasks: powerline.yaml
  tags: powerline

- include_tasks: ssh.yaml
  tags: ssh

- include_tasks: tmux.yaml
  tags: tmux

- include_tasks: utiliti-packages.yaml
  tags: utiliti-packages

- include_tasks: vim.yaml
  tags: vim

