# Tasks to include
#
# sh -c "$(head -4 main.yaml | tail -1 | sed 's/^# //')"
# head -5 main.yaml > new.main.yaml && for var in $(ls | grep -v "main.yaml" | sed 's/\.yaml$//' | sort); do printf "%s import_tasks: %s\n  tags: %s\n\n" "-" "${var}" "${var}";done >> new.main.yaml && mv new.main.yaml main.yaml
#
- import_tasks: gitmultirepo.yaml
  tags: gitmultirepo

- import_tasks: iterm2.yaml
  tags: iterm2

- import_tasks: ssh.yaml
  tags: ssh

- import_tasks: tmux.yaml
  tags: tmux

- import_tasks: utility-packages.yaml
  tags: utility-packages

- import_tasks: ipython.yaml
  tags: ipython
