- name: "Run this task before homebrew_cask module, so that sudo cache gets refreshed."
  command: "echo none"
  become: yes
  changed_when: false

- name: "Ensure latest minikube with brew"
  homebrew_cask: name=minikube state=latest
