# Virtualbox
- name: "Ensure homebrew cask virtualbox absent, --extra-vars reinstall_brew_casks=yes"
  homebrew_cask: name=virtualbox state=absent
  when: reinstall_brew_casks | default('no') | bool

- name: "Ensure homebrew cask virtualbox present"
  homebrew_cask: name=virtualbox state=latest

