# Openstack client

- name: "Ensure openstackclient present with pip"
  pip: name=python-openstackclient state=present
  tags: openstackclient

- name: "install openstackclient bash_completion DEBUG"
  debug: msg = "openstack complete > {{ user_bash_completions_directory }}/openstack"
  when: user_bash_completions_directory is defined
  tags: openstackclient

- name: "install openstackclient bash_completion"
  shell: openstack complete > {{ user_bash_completions_directory }}/openstack
  when: user_bash_completions_directory is defined
  tags: openstackclient
